services:
  db:
    image: mysql:8
    container_name: mysql-lab
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learninglab
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - DB_DSN=user:pass@tcp(db:3306)/learninglab
    command: ["./app"]